title: Don's awesome title
author: Don Balbieran
email: donbalbieran@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Don's awesome description for his awesome site!
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
